import type { Metadata } from "next";
import { Lato } from "next/font/google";

import Navbar from "./common/nav-bar/nav-bar";

import "./globals.css";
import "bootstrap/dist/css/bootstrap.min.css";
import DarkMode from "./utils/dark-mode";

const lato = Lato({
  subsets: ["latin"],
  weight: ["100", "300", "400", "700", "900"],
  variable: "--font-lato",
});
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${lato.variable} `}>
        <DarkMode>
          <Navbar />
          {children}
        </DarkMode>
      </body>
    </html>
  );
}
